import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const serverUrl = "http://localhost:4000";

export default function Home() {
  const pingServer = async () => {
    // const resp = await fetch("http://localhost:4000/api");
    const resp = await fetch(`${serverUrl}/api`);
    const data = await resp.json();
    console.log(data);
  };

  const pingSmiteServer = async () => {
    const resp = await fetch("http://localhost:4000/smiteapi");
    const data = await resp.json();
    console.log(data);
  };

  const createSession = async () => {
    const resp = await fetch("http://localhost:4000/createsession");
    const data = await resp.json();
    console.log(data);
  };

  const handlePing = () => {
    pingServer();
  };

  const handleSmitePing = () => {
    pingSmiteServer();
  };

  const handleCreateSession = () => {
    createSession();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <button onClick={() => handlePing()}>Ping server</button>
          <button onClick={() => handleSmitePing()}>Ping Smite API</button>
          <button onClick={() => handleCreateSession()}>Create Session</button>
        </div>
      </main>
    </>
  );
}
